
package br.diego.WsVendaClient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsVenda", targetNamespace = "http://webservicesjax.diego.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsVenda {


    /**
     * 
     * @return
     *     returns br.diego.WsVendaClient.Venda
     * @throws IOException_Exception
     * @throws ServletException_Exception
     */
    @WebMethod
    @WebResult(name = "resultVenda", targetNamespace = "")
    @RequestWrapper(localName = "fecharVenda", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsVendaClient.FecharVenda")
    @ResponseWrapper(localName = "fecharVendaResponse", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsVendaClient.FecharVendaResponse")
    public Venda fecharVenda()
        throws IOException_Exception, ServletException_Exception
    ;

}
