
package br.diego.WsVendaClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WsVendaService", targetNamespace = "http://webservicesjax.diego.br/", wsdlLocation = "http://localhost:8080/lab060922/WsVenda?wsdl")
public class WsVendaService
    extends Service
{

    private final static URL WSVENDASERVICE_WSDL_LOCATION;
    private final static WebServiceException WSVENDASERVICE_EXCEPTION;
    private final static QName WSVENDASERVICE_QNAME = new QName("http://webservicesjax.diego.br/", "WsVendaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab060922/WsVenda?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSVENDASERVICE_WSDL_LOCATION = url;
        WSVENDASERVICE_EXCEPTION = e;
    }

    public WsVendaService() {
        super(__getWsdlLocation(), WSVENDASERVICE_QNAME);
    }

    public WsVendaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSVENDASERVICE_QNAME, features);
    }

    public WsVendaService(URL wsdlLocation) {
        super(wsdlLocation, WSVENDASERVICE_QNAME);
    }

    public WsVendaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSVENDASERVICE_QNAME, features);
    }

    public WsVendaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsVendaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WsVenda
     */
    @WebEndpoint(name = "WsVendaPort")
    public WsVenda getWsVendaPort() {
        return super.getPort(new QName("http://webservicesjax.diego.br/", "WsVendaPort"), WsVenda.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsVenda
     */
    @WebEndpoint(name = "WsVendaPort")
    public WsVenda getWsVendaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservicesjax.diego.br/", "WsVendaPort"), WsVenda.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSVENDASERVICE_EXCEPTION!= null) {
            throw WSVENDASERVICE_EXCEPTION;
        }
        return WSVENDASERVICE_WSDL_LOCATION;
    }

}
