
package br.diego.WsProdutoClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsProduto", targetNamespace = "http://webservicesjax.diego.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsProduto {


    /**
     * 
     * @param paramProduto
     */
    @WebMethod(operationName = "Update")
    @RequestWrapper(localName = "Update", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsProdutoClient.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsProdutoClient.UpdateResponse")
    public void update(
        @WebParam(name = "paramProduto", targetNamespace = "")
        Produto paramProduto);

    /**
     * 
     * @param paramProduto
     */
    @WebMethod(operationName = "Create")
    @RequestWrapper(localName = "Create", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsProdutoClient.Create")
    @ResponseWrapper(localName = "CreateResponse", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsProdutoClient.CreateResponse")
    public void create(
        @WebParam(name = "paramProduto", targetNamespace = "")
        Produto paramProduto);

    /**
     * 
     * @param paramId
     */
    @WebMethod(operationName = "Delete")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsProdutoClient.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsProdutoClient.DeleteResponse")
    public void delete(
        @WebParam(name = "paramId", targetNamespace = "")
        Long paramId);

    /**
     * 
     * @return
     *     returns java.util.List<br.diego.WsProdutoClient.Produto>
     */
    @WebMethod(operationName = "Read")
    @WebResult(name = "returnRead", targetNamespace = "")
    @RequestWrapper(localName = "Read", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsProdutoClient.Read")
    @ResponseWrapper(localName = "ReadResponse", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsProdutoClient.ReadResponse")
    public List<Produto> read();

}
