
package br.diego.WsEntregaClient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsEntrega", targetNamespace = "http://webservicesjax.diego.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsEntrega {


    /**
     * 
     * @return
     *     returns br.diego.WsEntregaClient.Entrega
     * @throws ServletException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "resultadoEntrega", targetNamespace = "")
    @RequestWrapper(localName = "fecharEntrega", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsEntregaClient.FecharEntrega")
    @ResponseWrapper(localName = "fecharEntregaResponse", targetNamespace = "http://webservicesjax.diego.br/", className = "br.diego.WsEntregaClient.FecharEntregaResponse")
    public Entrega fecharEntrega()
        throws IOException_Exception, ServletException_Exception
    ;

}
